# Default values for harness-delegate chart.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

# These are the required values that are needed for harness-delegate
# chart deployment. You can download these account specific values by
# going to Harness > Setup > Installations page

# Account Id to which the delegate will be connecting
accountId: ""
# Account Secret
accountSecret: ""
# Delegate Token
delegateToken: ""
# Short 6 character identifier of the account
accountIdShort: ""


# These are the prepopulated default values that are needed for
# harness-delegate chart deployment

delegateName: harness-delegate
# Namespace in which delegate will be installed
namespace: harness-delegate

deployMode: "KUBERNETES"

delegateDockerImage: harness/delegate:latest

# For connecting to Harness production SAAS environment, leave these
# values as it is. For on-prem installation, these will be overriden
# and you can download at Harness > Setup > Installations page
managerHostAndPort: https://app.harness.io
watcherStorageUrl: https://app.harness.io/storage/wingswatchers
watcherCheckLocation: watcherprod.txt
remoteWatcherUrlCdn: ""
delegateStorageUrl: https://app.harness.io/storage/wingsdelegates
delegateCheckLocation: delegateprod.txt
useCdn: false
cdnUrl: https://storage-prod.harness.io
jreVersion: 1.8.0_242

# If the harness delegate should go through proxy then set it to true
proxyManager: "true"
# If the proxy doesn't support web socket (wss) protocol then set it
# to true
pollForTasks: "false"

# Proxy settings if the delegate will be running behind proxy
proxyHost: ""
proxyPort: ""
proxyUser: ""
proxyPassword: ""

# Allowed values are http or https
proxyScheme: ""

# Enter a comma separated list of suffixes for which proxy is not
# required. Do not use leading wildcards (.company.com,specifichost)
# (optional):
noProxy: ""

# Id of the delegate profile that needs to run when the delegate is
# coming up
delegateProfile: ""

# Helm version to be installed in delegate
helmDesiredVersion: ""

# Path to helm2 and helm3 binaries to be used during k8s/helm deployments
# otherwise harness installed default binaries will be used
helm3Path: ""
helmPath: ""

# Path for custom kustomize binary on the delegate to be used for kustomize deployments
# otherwise harness installed default binary will be used
kustomizePath: ""

# Path for custom oc binary on the delegate to be used for openshift deployments
# otherwise harness installed default binary will be used
ocPath: ""

# Path for custom kubectl binary on the delegate to be used for k8s deployments
# otherwise harness installed default binary will be used
kubectlPath: ""

# Controls if delegate client tools are installed in the background
# or they prevent delegate registering until they are installed. Default is in the background
installClientToolsInBackground: true